version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - db
      - redis

  nginx:
    image: openresty/openresty:latest
    platform: linux/amd64
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - my_network

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    networks:
      - my_network
    command: -c 'max_connections=1000'

  redis:
    image: redis:latest
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
