version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - db
      - redis

  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    networks:
      - my_network
    command: --max_connections=1000

  redis:
    image: redis:latest
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
