definitions:
  advertisement-api_internal_dto.AdCondition:
    properties:
      ageEnd:
        maximum: 100
        minimum: 1
        type: integer
      ageStart:
        maximum: 100
        minimum: 1
        type: integer
      country:
        items:
          type: string
        type: array
      gender:
        items:
          type: string
        type: array
      platform:
        items:
          type: string
        type: array
    type: object
  advertisement-api_internal_dto.AdCreationRequest:
    properties:
      conditions:
        $ref: '#/definitions/advertisement-api_internal_dto.AdCondition'
      endAt:
        type: string
      startAt:
        type: string
      title:
        type: string
    required:
    - endAt
    - startAt
    - title
    type: object
  advertisement-api_internal_dto.AdGetResponse:
    properties:
      endAt:
        type: string
      title:
        type: string
    type: object
  gin.H:
    additionalProperties: {}
    type: object
info:
  contact: {}
paths:
  /ad:
    get:
      consumes:
      - application/json
      description: get advertisements by params and conditions
      parameters:
      - description: Limit<1~100,default=5>
        in: query
        name: limit
        required: true
        type: integer
      - description: Age <1~100>
        in: query
        name: age
        type: integer
      - description: Gender <enum:M、F>
        in: query
        name: gender
        type: string
      - description: Country <enum:TW、JP 等符合 https://zh.wikipedia.org/wiki/ISO_3166-1
          >
        in: query
        name: country
        type: string
      - description: Platform <enum:android, ios, web>
        in: query
        name: platform
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/advertisement-api_internal_dto.AdGetResponse'
        "400":
          description: '{"error": "params error"}'
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: '{"error": "server error"}'
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get advertisements
      tags:
      - advertisements
    post:
      consumes:
      - application/json
      description: create a new advertisement
      parameters:
      - description: Create Advertisement
        in: body
        name: adCreationRequest
        required: true
        schema:
          $ref: '#/definitions/advertisement-api_internal_dto.AdCreationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "success"}'
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: '{"error": "params error"}'
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: '{"error": "server error"}'
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create advertisement
      tags:
      - advertisements
swagger: "2.0"
